org.gradle.jvmargs=-Xmx6g -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
kotlin.mpp.enableCInteropCommonization=true
kotlin.js.yarn=false
codexAgent.codexVersion=0.149.0
codexAgent.codexArchiveSha256=ab91c737ff50e5e1187582ffa316ba8b5341c250657c5c5d678a88b6dc7f4f71
codexAgent.codexBinarySha256=96ac7e010cc38b90e66fc0dc67f5baa343b61f5471c6625bb2694d7991e2bbe0
