package io.github.codex_agent_labs.codexagent.appserver.generator

import java.io.File
import java.security.MessageDigest
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.put
import kotlinx.serialization.json.putJsonArray

internal fun JsonObject.types(): List<String> = when (val type = get("type")) {
    is JsonArray -> type.map { it.jsonPrimitive.content }
    is JsonPrimitive -> listOf(type.content)
    else -> emptyList()
}

internal fun JsonObject.constantValue(): String? = get("const")?.jsonPrimitive?.content
    ?: (get("enum") as? JsonArray)?.singleOrNull()?.jsonPrimitive?.content

internal fun String.nullableIf(nullable: Boolean): String = if (nullable && !endsWith('?')) "$this?" else this

internal fun String.kotlinIdentifier(): String {
    val cleaned = replace(Regex("[^A-Za-z0-9_]"), "_").let {
        if (it.firstOrNull()?.isDigit() == true) "value_$it" else it
    }
    return if (cleaned in KOTLIN_KEYWORDS) "${cleaned}_" else cleaned
}

internal fun String.enumEntryName(): String = replace(Regex("([a-z0-9])([A-Z])"), "$1_$2")
    .replace(Regex("[^A-Za-z0-9]+"), "_")
    .trim('_')
    .uppercase()
    .ifEmpty { "EMPTY" }
    .let { if (it.first().isDigit()) "VALUE_$it" else it }

internal val KOTLIN_KEYWORDS = setOf(
    "as", "break", "class", "continue", "do", "else", "false", "for", "fun", "if", "in", "interface",
    "is", "null", "object", "package", "return", "super", "this", "throw", "true", "try", "typealias",
    "typeof", "val", "var", "when", "while",
)

internal fun updateProvenance(
    file: File,
    schema: File,
    thread: File,
    turn: File,
    outputs: List<File>,
) {
    val current = JSON.parseToJsonElement(file.readText()).jsonObject
    val updated = JsonObject(current.toMutableMap().apply {
        val completeSchemaPath = "codex-rs/app-server-protocol/schema/json/codex_app_server_protocol.schemas.json"
        val threadPath = "codex-rs/app-server-protocol/src/protocol/v2/thread.rs"
        val turnPath = "codex-rs/app-server-protocol/src/protocol/v2/turn.rs"
        val addedPaths = setOf(completeSchemaPath, threadPath, turnPath)
        val existingInputs = current.getValue("inputs").jsonArray.filterNot { input ->
            input.jsonObject.getValue("path").jsonPrimitive.content in addedPaths
        }
        put(
            "inputs",
            JsonArray(
                existingInputs + listOf(
                    provenanceInput(
                        completeSchemaPath,
                        "6802d1635345501032a4010552fda8372ec9396a",
                        schema,
                    ),
                    provenanceInput(
                        threadPath,
                        "75fe5091b188f1f2fc601fadd169dc737cba31bd",
                        thread,
                    ),
                    provenanceInput(
                        turnPath,
                        "0b2c092ec83a7c4c29827ad8c735db73ee61142a",
                        turn,
                    ),
                ),
            ),
        )
        put(
            "completeSchemaExtraction",
            JsonPrimitive("git show rust-v0.149.0:$completeSchemaPath"),
        )
        put("generator", buildJsonObject {
            put("version", GENERATOR_VERSION)
            put(
                "command",
                "./gradlew updateProtocol -PcodexProtocolSchema=/path/to/codex_app_server_protocol.schemas.json " +
                    "-PcodexProtocolCommon=/path/to/common.rs -PcodexProtocolThread=/path/to/thread.rs " +
                    "-PcodexProtocolTurn=/path/to/turn.rs",
            )
            putJsonArray("outputs") {
                outputs.forEach { output ->
                    add(buildJsonObject {
                        put("path", output.relativeTo(file.parentFile.parentFile.parentFile).invariantSeparatorsPath)
                        put("sha256", output.sha256())
                    })
                }
            }
        })
    })
    writeText(file, JSON.encodeToString(JsonObject.serializer(), updated) + "\n")
}

internal data class GeneratedFile(val name: String, val content: String)

internal fun generatedHeader(imports: String = ""): String = buildString {
    appendLine("// Generated by protocol-generator $GENERATOR_VERSION. Do not edit.")
    appendLine("@file:Suppress(\"unused\")")
    appendLine()
    appendLine("package io.github.codex_agent_labs.codexagent.appserver.protocol.generated")
    if (imports.isNotBlank()) {
        appendLine()
        appendLine(imports)
    }
    appendLine()
}

internal fun modelHeader(): String = generatedHeader(
    """
    import kotlinx.serialization.DeserializationStrategy
    import kotlinx.serialization.SerialName
    import kotlinx.serialization.Serializable
    import kotlinx.serialization.json.JsonContentPolymorphicSerializer
    import kotlinx.serialization.json.JsonElement
    import kotlinx.serialization.json.JsonObject
    import kotlinx.serialization.json.jsonObject
    import kotlinx.serialization.json.jsonPrimitive
    """.trimIndent(),
)

internal fun rebalanceLastChunk(chunks: MutableList<MutableList<String>>) {
    if (chunks.size < 2) return
    val last = chunks.last()
    while (modelHeader().lineCount() + last.sumOf(String::lineCount) < MIN_GENERATED_LINES) {
        val previous = chunks[chunks.lastIndex - 1]
        val moved = previous.lastOrNull() ?: break
        val previousAfterMove = modelHeader().lineCount() + previous.dropLast(1).sumOf(String::lineCount)
        val lastAfterMove = modelHeader().lineCount() + last.sumOf(String::lineCount) + moved.lineCount()
        if (previousAfterMove < MIN_GENERATED_LINES || lastAfterMove > MAX_GENERATED_LINES) break
        previous.removeLast()
        last.add(0, moved)
    }
    val lastLines = modelHeader().lineCount() + last.sumOf(String::lineCount)
    if (lastLines >= MIN_GENERATED_LINES) return
    val previous = chunks[chunks.lastIndex - 1]
    val mergedLines = modelHeader().lineCount() + previous.sumOf(String::lineCount) + last.sumOf(String::lineCount)
    check(mergedLines <= MAX_GENERATED_LINES) { "Unable to create a model shard of at least $MIN_GENERATED_LINES lines" }
    previous += last
    chunks.removeLast()
}

internal fun writeGeneratedSources(directory: File, sources: List<GeneratedFile>) {
    val desired = sources.map(GeneratedFile::name).toSet()
    sources.forEach { source -> writeText(directory.resolve(source.name), source.content.trimEnd() + "\n") }
    directory.listFiles().orEmpty()
        .filter { it.name.startsWith("GeneratedProtocol") && it.extension == "kt" && it.name !in desired }
        .forEach { check(it.delete()) { "Unable to delete stale generated source ${it.path}" } }
}

internal fun String.lineCount(): Int = lineSequence().count()

internal const val MIN_GENERATED_LINES = 100
internal const val PREFERRED_GENERATED_LINES = 220
internal const val MAX_GENERATED_LINES = 300
internal const val MODEL_HEADER_LINES = 14

internal fun provenanceInput(path: String, gitBlob: String, file: File) = buildJsonObject {
    put("path", path)
    put("gitBlob", gitBlob)
    put("sha256", file.sha256())
}

internal fun writeText(file: File, value: String) {
    writeBytes(file, value.toByteArray())
}

internal fun writeBytes(file: File, value: ByteArray) {
    file.parentFile.mkdirs()
    val temporary = File(file.parentFile, ".${file.name}.next")
    temporary.writeBytes(value)
    check(temporary.renameTo(file) || (file.delete() && temporary.renameTo(file))) {
        "Unable to replace ${file.path}"
    }
}

internal fun File.sha256(): String = inputStream().use { input ->
    val digest = MessageDigest.getInstance("SHA-256")
    val buffer = ByteArray(DEFAULT_BUFFER_SIZE)
    while (true) {
        val count = input.read(buffer)
        if (count < 0) break
        digest.update(buffer, 0, count)
    }
    digest.digest().joinToString("") { "%02x".format(it.toInt() and 0xff) }
}

internal fun String.escape(): String = replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\\$")

internal fun String.kotlinTypeName(): String = split(Regex("[^A-Za-z0-9]+")).filter(String::isNotEmpty)
    .joinToString("") { part -> part.replaceFirstChar(Char::uppercase) }
    .let { if (it.firstOrNull()?.isDigit() == true) "Method$it" else it }
