"""Synthetic installed cache; never invokes Gradle or downloads a distribution."""

from pathlib import Path
import tempfile
import unittest

from ci.products.gradle_bootstrap import require_preprovisioned_gradle


PROPERTIES = b"""distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionSha256Sum=2ab2958f2a1e51120c326cad6f385153bb11ee93b3c216c5fccebfdfbb7ec6cb
distributionUrl=https\\://services.gradle.org/distributions/gradle-9.4.1-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
"""


class GradleBootstrapTest(unittest.TestCase):
    def setUp(self):
        temporary = tempfile.TemporaryDirectory()
        self.addCleanup(temporary.cleanup)
        self.home = Path(temporary.name).resolve()
        # Actual PathAssembler locator for the pinned source URL; not generated by the helper.
        self.cache = self.home / "wrapper/dists/gradle-9.4.1-bin/arn2x92ynaizyzdaamcbpbhtj"
        self.installation = self.cache / "gradle-9.4.1"
        self.launcher = self.installation / "lib/gradle-launcher-9.4.1.jar"
        self.launcher.parent.mkdir(parents=True)
        self.launcher.write_bytes(b"synthetic launcher; no authenticity claim")
        self.marker = self.cache / "gradle-9.4.1-bin.zip.ok"
        self.marker.touch()
        self.environment = {"GRADLE_USER_HOME": str(self.home)}

    def test_installed_fast_path_is_read_only_and_uses_exact_gradle_cache_locator(self):
        before = sorted(str(path.relative_to(self.home)) for path in self.home.rglob("*"))
        self.assertEqual(self.installation, require_preprovisioned_gradle(PROPERTIES, self.environment))
        self.assertEqual(before, sorted(str(path.relative_to(self.home)) for path in self.home.rglob("*")))

    def test_missing_marker_or_launcher_fails_without_bootstrap(self):
        for path in (self.marker, self.launcher):
            with self.subTest(path=path):
                original = path.read_bytes()
                path.unlink()
                with self.assertRaises((ValueError, OSError)):
                    require_preprovisioned_gradle(PROPERTIES, self.environment)
                self.assertFalse(path.exists())
                path.write_bytes(original)

    def test_ambiguous_empty_and_symbolic_installations_fail(self):
        extra = self.cache / "other"
        extra.mkdir()
        with self.assertRaises(ValueError):
            require_preprovisioned_gradle(PROPERTIES, self.environment)
        extra.rmdir()
        self.launcher.write_bytes(b"")
        with self.assertRaises(ValueError):
            require_preprovisioned_gradle(PROPERTIES, self.environment)
        self.launcher.unlink()
        self.launcher.symlink_to(self.marker)
        with self.assertRaises(ValueError):
            require_preprovisioned_gradle(PROPERTIES, self.environment)

    def test_unpinned_or_redirected_layout_and_relative_home_fail(self):
        for original, replacement in ((b"GRADLE_USER_HOME", b"PROJECT"),
                (b"wrapper/dists", b"../dists"), (b"https\\:", b"http\\:"),
                (b"2ab2958f", b"not-a-pin")):
            with self.subTest(original=original), self.assertRaises(ValueError):
                require_preprovisioned_gradle(PROPERTIES.replace(original, replacement), self.environment)
        with self.assertRaises(ValueError):
            require_preprovisioned_gradle(PROPERTIES, {"GRADLE_USER_HOME": "relative"})
