import java.io.File

/**
 * Source/metadata consistency only. The caller authenticates the immutable original
 * source snapshot, package, versions and original path/SDK context independently.
 * It must also run the existing process/report/task-outcome gate; this function
 * neither executes Gradle nor grants original job, toolchain or receipt authority.
 * Unsupported historical generated bytes fail rather than executing old source.
 */
internal fun verifyOriginalSdkFacadeConsumerInputs(
    sourceSnapshot: File,
    consumerInputs: File,
    packageStage: File,
    target: String,
    contractVersion: String,
    runtimeVersion: String,
    sdkVersion: String,
    kotlinVersion: String,
    originalExecutionDirectory: String,
    androidSdkDirectory: String,
    compilerInputs: File,
    forbiddenPath: String = "",
) {
    val task = sdkFacadeConsumerCompileTasks[target] ?: error("Unsupported original facade target")
    val outcomes = originalFacadeOutcomePath(originalExecutionDirectory)
    val separator = if (originalExecutionDirectory.startsWith('/')) '/' else '\\'
    val originalCompiler = originalExecutionDirectory.substringBeforeLast(separator) + separator + "compiler-inputs.json"
    requireApplePackagePathWithoutSymlinks(compilerInputs, "original facade compiler inputs")
    check(compilerInputs.isFile) { "Original facade compiler inputs are missing" }
    val compilerBefore = compilerInputs.releaseDigest()
    val inputs = listOf(sourceSnapshot, consumerInputs, packageStage)
    requireOriginalAppleSnapshotDisjoint(compilerInputs, inputs)
    fun inventories() = inputs.map { directory ->
        requireApplePackagePathWithoutSymlinks(directory, "original facade input")
        check(directory.isDirectory) { "Original facade input directory is missing" }
        verifiedRegularFiles(directory).mapValues { it.value.releaseDigest() }
    }
    inputs.forEachIndexed { index, directory ->
        requireOriginalAppleSnapshotDisjoint(directory, inputs.filterIndexed { other, _ -> index != other })
    }
    val before = inventories()
    try {
        val template = sourceSnapshot.resolve("gradle/release/sdk-facade-consumer-template")
        val templateFiles = verifiedRegularFiles(template)
        check(templateFiles.keys.containsAll(setOf("build.gradle.kts", "settings.gradle.kts",
            "src/commonMain/kotlin/Consumer.kt"))) { "Original facade template is incomplete" }
        val initName = ".codex-consumer-task-outcomes.init.gradle.kts"
        check("local.properties" !in templateFiles && initName !in templateFiles) {
            "Original facade template contains generated consumer inputs"
        }
        val retained = verifiedRegularFiles(consumerInputs)
        check(retained.keys == templateFiles.keys + setOf("local.properties", initName)) {
            "Original facade consumer input inventory differs from the complete template and generated inputs"
        }
        templateFiles.forEach { (relative, original) ->
            check(original.readBytes().contentEquals(retained.getValue(relative).readBytes())) {
                "Original facade consumer template differs: $relative"
            }
        }
        check(retained.getValue("local.properties").readBytes().contentEquals(
            stagedConsumerLocalProperties(androidSdkDirectory).toByteArray(Charsets.UTF_8))) {
            "Original facade local.properties differs from independent Android SDK context"
        }
        val expectedScript = stagedConsumerOutcomeInitScript(listOf(task)) +
            stagedConsumerExecutionCaptureScript(outcomes) + sdkFacadeCompilerCaptureScript(target, originalCompiler)
        check(retained.getValue(initName).readBytes().contentEquals(expectedScript.toByteArray(Charsets.UTF_8))) {
            "Original facade init script differs from the fixed task and original capture path"
        }
        verifyImportedSdkFacadePublicationMetadata(packageStage, contractVersion, runtimeVersion,
            sdkVersion, kotlinVersion, forbiddenPath)
        val agp = Regex("id\\(\"com\\.android\\.kotlin\\.multiplatform\\.library\"\\) version \"([^\"]+)\"")
            .findAll(templateFiles.getValue("build.gradle.kts").readText()).toList().singleOrNull()
            ?.groupValues?.get(1) ?: error("Original facade Android plugin version is not exact")
        verifySdkFacadeCompilerCapture(compilerInputs, target, kotlinVersion, agp)
    } finally {
        check(inventories() == before) { "Original facade inputs changed during replay" }
        requireApplePackagePathWithoutSymlinks(compilerInputs, "original facade compiler inputs")
        check(compilerInputs.isFile && compilerInputs.releaseDigest() == compilerBefore) {
            "Original facade compiler inputs changed during replay"
        }
    }
}

/** Never resolves an original execution path against the replay host filesystem. */
private fun originalFacadeOutcomePath(directory: String): String {
    check(directory.none(Char::isISOControl)) { "Original facade execution directory is invalid" }
    val windows = Regex("^[A-Za-z]:\\\\").containsMatchIn(directory) || directory.startsWith("\\\\")
    val separator = if (windows) '\\' else '/'
    val remainder = when {
        windows && directory.startsWith("\\\\") -> directory.drop(2).also {
            check(it.split('\\').size >= 3) { "Original facade UNC directory is invalid" }
        }
        windows -> directory.drop(3)
        directory.startsWith('/') -> directory.drop(1)
        else -> error("Original facade execution directory must be absolute")
    }
    check((if (windows) '/' !in directory else '\\' !in directory) &&
        remainder.split(separator).all { it.isNotEmpty() && it != "." && it != ".." }) {
        "Original facade execution directory must be normalized"
    }
    return "$directory${separator}task-outcomes.json"
}
